---
site_name: Margin Chronicles
description: A collection of writing lessons found in speculative fiction stories.
font_type: serif
nav_links:
  guide: "style/index.html"
  list: "style/pages/index.html"
